#!/bin/bash


echo "Ir a Ruta"
cd /usr/local/bin

echo "renombrando file"
mv menu /usr/local/bin/menu2

echo "DESACARGANDO archivo"
wget https://raw.githubusercontent.com/Igmam21/Panel-de-Shoutcast-SSH/main/versiones/101/menu

echo "Dando permisos"
chmod 777 /usr/local/bin/menu

echo "removiendo archivo"
rm menu2



echo "////////////////////////////////////////////////////////////////////
/////////////////                                          ///////////////
////////////////       SCRIP ACTUALIZADO CON EXITO!         //////////////
////////////////                                            //////////////
//////////////////////////////////////////////////////////////////////////"
