#!/bin/bash


echo "Ir a Ruta"
cd /usr/local/bin


echo "renombrando file"
mv menu /usr/local/bin/menu2

echo "DESACARGANDO archivo"
wget https://raw.githubusercontent.com/Igmam21/Panel-de-Shoutcast-SSH/main/menu

echo "Dando permisos"
chmod 777 /usr/local/bin/menu

echo "removiendo archivo"
mm menu2



echo -e"////////////////////////////////////////////////////////////////////
/////////////////                                          ///////////////
////////////////       \e[1;33mSCRIP ACTUALIZADO CON EXITO!\e[0m        //////////////
////////////////                                            //////////////
//////////////////////////////////////////////////////////////////////////"
